# Generated by Django 4.1.5 on 2023-03-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0003_rename_fio_student_fio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='tg_id',
            new_name='telegram_id',
        ),
    ]
