# Generated by Django 4.1.5 on 2023-03-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0004_rename_tg_id_student_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
